version: "3"
services:
      jenkins:
          image: jenkinsci/jenkins
          privileged: true
          user: root
          ports:
                  - "8080:8080"
          container_name: jenkins
#          links:
#                  - artifactory
#                  - sonarqube
          volumes:
                  - ./jenkins:/var/jenkins_home:rw
#                  - /var/run/docker.sock:/var/run/docker.sock
#                  - /usr/bin/docker:/usr/bin/docker 